[package]
name = "ctf-backend"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
actix-cors = "0.5.4"
actix-files = "0.5.0"
actix-rt = "2.1.0"
actix-web = "3.3.2"
butane = "0.2.1"
env_logger = "0.8.3"
http = "0.2.3"
lazy_static = "1.4.0"

[dev-dependencies]
actix-http = "2.2.0"
